"""empty message

Revision ID: 0ec68daeb6c8
Revises: 379e38fc35eb
Create Date: 2017-09-07 14:29:28.679000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec68daeb6c8'
down_revision = '379e38fc35eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_recapitulations', sa.Column('budgeted_revenue', sa.DECIMAL(), nullable=True))
    op.add_column('progress_recapitulations', sa.Column('realized_spending', sa.DECIMAL(), nullable=True))
    op.drop_column('progress_recapitulations', 'realized_revenue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_recapitulations', sa.Column('realized_revenue', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('progress_recapitulations', 'realized_spending')
    op.drop_column('progress_recapitulations', 'budgeted_revenue')
    # ### end Alembic commands ###
