"""empty message

Revision ID: 379e38fc35eb
Revises: 
Create Date: 2017-09-07 14:00:45.298000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e38fc35eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_key', table_name='regions')
    op.create_index('ix_url_key', 'regions', ['url_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_key', table_name='regions')
    op.create_index('ix_url_key', 'regions', ['url_key'], unique=True)
    # ### end Alembic commands ###
