"""empty message

Revision ID: a2b182dfec06
Revises: 
Create Date: 2017-10-13 14:57:22.752000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b182dfec06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pr_ix_fk_region_id', 'progress_recapitulations', ['fk_region_id'], unique=False)
    op.create_index('pt_ix_fk_region_id', 'progress_timelines', ['fk_region_id'], unique=False)
    op.drop_index('regions_ix_url_key', table_name='regions')
    op.drop_column(u'regions', 'url_key')
    op.create_index('sk_ix_fk_region_id', 'siskeudes_kegiatans', ['fk_region_id'], unique=False)
    op.create_index('spr_ix_fk_region_id', 'siskeudes_penerimaan_rincis', ['fk_region_id'], unique=False)
    op.create_index('sp_ix_fk_region_id', 'siskeudes_penerimaans', ['fk_region_id'], unique=False)
    op.create_index('spg_ix_fk_region_id', 'siskeudes_penganggarans', ['fk_region_id'], unique=False)
    op.create_index('ssppb_ix_fk_region_id', 'siskeudes_spp_buktis', ['fk_region_id'], unique=False)
    op.create_index('ssppr_ix_fk_region_id', 'siskeudes_spp_rincis', ['fk_region_id'], unique=False)
    op.create_index('sspp_ix_fk_region_id', 'siskeudes_spps', ['fk_region_id'], unique=False)
    op.create_index('sr_ix_fk_region_id', 'spending_recapitulations', ['fk_region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sr_ix_fk_region_id', table_name='spending_recapitulations')
    op.drop_index('sspp_ix_fk_region_id', table_name='siskeudes_spps')
    op.drop_index('ssppr_ix_fk_region_id', table_name='siskeudes_spp_rincis')
    op.drop_index('ssppb_ix_fk_region_id', table_name='siskeudes_spp_buktis')
    op.drop_index('spg_ix_fk_region_id', table_name='siskeudes_penganggarans')
    op.drop_index('sp_ix_fk_region_id', table_name='siskeudes_penerimaans')
    op.drop_index('spr_ix_fk_region_id', table_name='siskeudes_penerimaan_rincis')
    op.drop_index('sk_ix_fk_region_id', table_name='siskeudes_kegiatans')
    op.add_column(u'regions', sa.Column('url_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('regions_ix_url_key', 'regions', ['url_key'], unique=False)
    op.drop_index('pt_ix_fk_region_id', table_name='progress_timelines')
    op.drop_index('pr_ix_fk_region_id', table_name='progress_recapitulations')
    # ### end Alembic commands ###
