"""empty message

Revision ID: df08dcb375ec
Revises: 
Create Date: 2017-09-25 11:56:47.966000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df08dcb375ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siskeudes_penganggarans')
    op.drop_table('siskeudes_spp_rincis')
    op.drop_table('regions')
    op.drop_table('siskeudes_spps')
    op.drop_table('progress_timelines')
    op.drop_table('spending_recapitulations')
    op.drop_table('siskeudes_spp_buktis')
    op.drop_table('siskeudes_penerimaans')
    op.drop_table('progress_recapitulations')
    op.drop_table('siskeudes_kegiatans')
    op.drop_table('spending_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_types',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('spending_types_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'spending_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('siskeudes_kegiatans',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sk_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_bidang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nama_bidang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_kegiatan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nama_kegiatan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('waktu', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nama_pptkd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keluaran', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pagu', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pagu_pak', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_kegiatans_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'siskeudes_kegiatans_pkey')
    )
    op.create_table('progress_recapitulations',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('budgeted_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('transferred_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('realized_spending', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'progress_recapitulations_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'progress_recapitulations_pkey')
    )
    op.create_table('siskeudes_penerimaans',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_penerimaans_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('pid', name=u'siskeudes_penerimaans_pkey')
    )
    op.create_table('siskeudes_spp_buktis',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_rincian', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_spp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tahun', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_kegiatan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sumber_dana', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tanggal', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nama_penerima', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nilai', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rekening_bank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nama_bank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('npwp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_spp_buktis_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('pid', name=u'siskeudes_spp_buktis_pkey')
    )
    op.create_table('spending_recapitulations',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('budgeted', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('realized', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fk_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'spending_recapitulations_fk_region_id_fkey'),
    sa.ForeignKeyConstraint(['fk_type_id'], [u'spending_types.id'], name=u'spending_recapitulations_fk_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'spending_recapitulations_pkey')
    )
    op.create_table('progress_timelines',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transferred_dds', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('transferred_add', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('transferred_pbh', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('realized_spending', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'progress_timelines_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'progress_timelines_pkey')
    )
    op.create_table('siskeudes_spps',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tahun', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tanggal', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('jenis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jumlah', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('potongan', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_spps_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('pid', name=u'siskeudes_spps_pkey')
    )
    op.create_table('regions',
    sa.Column('id', sa.VARCHAR(length=128), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('is_kelurahan', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fk_parent_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text(u"'-infinity'::timestamp without time zone"), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), server_default=sa.text(u"'-infinity'::timestamp without time zone"), autoincrement=False, nullable=False),
    sa.Column('is_in_scope', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.Column('is_lokpri', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_parent_id'], [u'regions.id'], name=u'FK_public.regions_public.regions_fk_parent_id'),
    sa.PrimaryKeyConstraint('id', name=u'PK_public.regions'),
    postgresql_ignore_search_path=False
    )
    op.create_table('siskeudes_spp_rincis',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_spp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tahun', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_kegiatan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sumber_dana', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nilai', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_spp_rincis_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('pid', name=u'siskeudes_spp_rincis_pkey')
    )
    op.create_table('siskeudes_penganggarans',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kode_kegiatan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kode_rekening', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uraian', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sumber_dana', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('satuan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jumlah_satuan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('harga_satuan', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('anggaran', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('jumlah_satuan_pak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('harga_satuan_pak', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('anggaran_pak', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('perubahan', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fk_region_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_region_id'], [u'regions.id'], name=u'siskeudes_penganggarans_fk_region_id_fkey'),
    sa.PrimaryKeyConstraint('pid', name=u'siskeudes_penganggarans_pkey')
    )
    # ### end Alembic commands ###
