"""empty message

Revision ID: 1a3ba6cc8d9d
Revises: 
Create Date: 2017-12-22 14:10:30.419000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3ba6cc8d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
