"""empty message

Revision ID: 233440973863
Revises: bdc650163e58
Create Date: 2018-01-04 23:39:22.409000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233440973863'
down_revision = 'bdc650163e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'vaccines_fk_growth_id_fkey', 'vaccines', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'vaccines_fk_growth_id_fkey', 'vaccines', 'growths', ['fk_growth_id'], ['id'])
    # ### end Alembic commands ###
