"""empty message

Revision ID: bdc650163e58
Revises: db51d718f518
Create Date: 2018-01-04 17:31:48.747000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc650163e58'
down_revision = 'db51d718f518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'childs', sa.Column('bpjs', sa.String(), nullable=True))
    op.drop_column(u'childs', 'is_bpjs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'childs', sa.Column('is_bpjs', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column(u'childs', 'bpjs')
    # ### end Alembic commands ###
