"""empty message

Revision ID: db51d718f518
Revises: 9dcea1505a63
Create Date: 2018-01-04 15:44:54.551000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db51d718f518'
down_revision = '9dcea1505a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'flag')
    # ### end Alembic commands ###
