"""empty message

Revision ID: 1f6bea2cd322
Revises: 
Create Date: 2017-11-16 16:29:43.872000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6bea2cd322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'summaries', sa.Column('apbdes_total', sa.DECIMAL(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_area', sa.DECIMAL(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_communication', sa.String(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_electricity', sa.String(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_potential', sa.String(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_water', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'summaries', 'pemetaan_water')
    op.drop_column(u'summaries', 'pemetaan_potential')
    op.drop_column(u'summaries', 'pemetaan_electricity')
    op.drop_column(u'summaries', 'pemetaan_communication')
    op.drop_column(u'summaries', 'pemetaan_area')
    op.drop_column(u'summaries', 'apbdes_total')
    # ### end Alembic commands ###
