"""empty message

Revision ID: 6c3ded43a640
Revises: 1f6bea2cd322
Create Date: 2017-11-22 13:10:22.818000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3ded43a640'
down_revision = '1f6bea2cd322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'summaries', sa.Column('pemetaan_desa_area', sa.DECIMAL(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_dusun_area', sa.DECIMAL(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_electricity_available_kk', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_electricity_total_kk', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_potential_farmland', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_potential_forest', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_potential_orchard', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_water_ditch', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_water_river', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_water_spring', sa.Integer(), nullable=True))
    op.add_column(u'summaries', sa.Column('penganggaran_budgeted_revenue', sa.DECIMAL(), nullable=True))
    op.drop_column(u'summaries', 'pemetaan_potential')
    op.drop_column(u'summaries', 'pemetaan_electricity')
    op.drop_column(u'summaries', 'apbdes_total')
    op.drop_column(u'summaries', 'pemetaan_area')
    op.drop_column(u'summaries', 'pemetaan_water')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'summaries', sa.Column('pemetaan_water', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_area', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column(u'summaries', sa.Column('apbdes_total', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_electricity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'summaries', sa.Column('pemetaan_potential', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column(u'summaries', 'penganggaran_budgeted_revenue')
    op.drop_column(u'summaries', 'pemetaan_water_spring')
    op.drop_column(u'summaries', 'pemetaan_water_river')
    op.drop_column(u'summaries', 'pemetaan_water_ditch')
    op.drop_column(u'summaries', 'pemetaan_potential_orchard')
    op.drop_column(u'summaries', 'pemetaan_potential_forest')
    op.drop_column(u'summaries', 'pemetaan_potential_farmland')
    op.drop_column(u'summaries', 'pemetaan_electricity_total_kk')
    op.drop_column(u'summaries', 'pemetaan_electricity_available_kk')
    op.drop_column(u'summaries', 'pemetaan_dusun_area')
    op.drop_column(u'summaries', 'pemetaan_desa_area')
    # ### end Alembic commands ###
