from progress_recapitulation import ProgressRecapitulationRepository
from progress_timeline import ProgressTimelineRepository
from region import RegionRepository
from sideka_content import SidekaContentRepository
from sideka_desa import SidekaDesaRepository
from siskeudes_kegiatan import SiskeudesKegiatanRepository
from siskeudes_penerimaan import SiskeudesPenerimaanRepository
from siskeudes_penerimaan_rinci import SiskeudesPenerimaanRinciRepository
from siskeudes_penganggaran import SiskeudesPenganggaranRepository
from siskeudes_spp import SiskeudesSppRepository
from siskeudes_spp_bukti import SiskeudesSppBuktiRepository
from siskeudes_spp_rinci import SiskeudesSppRinciRepository
from budget_recapitulation import BudgetRecapitulationRepository
from budget_type import BudgetTypeRepository


