from admin import app as AdminController
from kegiatan import app as KegiatanController
from penerimaan import app as PenerimaanController
from penganggaran import app as PenganggaranController
from progress import app as ProgressController
from region import app as RegionController
from budget import app as BudgetController
from spp import app as SppController
from likelihood import app as LikelihoodController
